---

- hosts: localhost
  connection: local     # won't require ssh
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade system
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Install packages
      apt:
        name:
          - nginx
          - screenfetch
          # - docker.io
          - htop
          - speedtest-cli
          - mesa-utils
        state: present
      when: ansible_os_family == "Debian"
