---

- hosts: all
  become: true
  tasks:

  - name: Install packages
    apt:
      update_cache: true
      name:
        - apache2
        - nginx
        - screenfetch
        - git
    when: ansible_distribution == "Ubuntu"
