---

- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Upgrade system
  become: true
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install packages
  # use sudo only for apt modules
  # (this fixes dotfiles being copied to root user in 'template'and 'copy' modules)
  become: true
  apt:
    name:
      - nginx
      - screenfetch
      - docker.io
      - htop
      - speedtest-cli
      - mesa-utils
      - tmux
    state: present
  when: ansible_os_family == "Debian"

- name: Enable and Start Docker
  become: true
  service:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  become: true
  user:
    name: "{{ user_name }}"
    groups: docker
    append: true

- name: Copy bash_aliases
  tags: config
  template:
    src: bash_aliases.j2                     # if .j2, use templates
    dest: "{{ user_home }}/.bash_aliases"    # dynamically resolves home directory
    owner: "{{ user_name }}"                 # automatically matches username
    group: "{{ user_name }}"
    mode: '0644'

- name: Copy tmux config
  tags: config
  template:
    src: tmux.conf.j2
    dest: "{{ user_home }}/.tmux.conf"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Copy vimrc
  tags: config
  copy:
    src: vimrc                      # if not .j2, use copy module
    dest: "{{ user_home }}/.vimrc"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Copy logos
  tags: pics
  copy:
    src: pictures/                  # copy contents of pictures dir
    dest: "{{ user_home }}/Pictures/"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'                                  

